In [2]:
numbers=[1,2,3,4]
squares=[]
for i in numbers:
  squares.append(i*i)
  print(squares)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]


In [3]:
squares2=list(map(lambda i:i*i,numbers))

In [4]:
print(squares2)

[1, 4, 9, 16]


In [8]:
#numpy
#ndarray---- n dimensional array
import numpy as np
list1=[1,2,3,4]
np1=np.array([list1])
print(np1)
print(type(np1))

[[1 2 3 4]]
<class 'numpy.ndarray'>


In [10]:
np2=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np2)
print(type(np2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [14]:
print(np2[2])

[7 8 9]


In [15]:
print(len(np1))
print(len(np2))

1
3


In [17]:
random1=np.ones((3,3),dtype='int')
print(random1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
random2 = np.full((3,3)," ")
print(random2)

[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]


In [20]:
def check_win(board,user_value):
  for i in range(0,3):
    if(np.all(board[i]==user_value) or np.all(board[:i]==user_value)):
      return True
    if(np.all(np.diag(board)==user_value)):
      return True
    return False

In [28]:
def game_starts():
  board=np.full((3,3)," ")
  player1=input("Enter you name player 1")
  player2=input("Enter you name player 2")
  check=player1
  while True:
    if check == player1:
      print(player1, "Its your choice")
    else:
      print(player2,"Its your choice")
    print(board)
    row=int(input("Enter row"))
    col=int(input("Enter col"))
    if board[row][col]!=" ":
      print("It is already occupied")
      continue
    if check==player1:
       board[row][col]='x'
       if(check_win(board,'x')):
          print(board)
          print(player1,"won")
          break
       else:
         board[row][col]='o'
         if(check_win(board,'o')):
          print(board)
          print(player1,"won")
          break
       if check==player1:
          check=player2
       else:
          check=player1

In [30]:
print("WELCOME TO TIC TAC TOE")
play1=input("Are you ready yes or no")
if(play1=="yes"):
  game_starts()
else:
  print("You choose not to play" )

WELCOME TO TIC TAC TOE
Are you ready yes or noyes
Enter you name player 1navya
Enter you name player 2akshaya
navya Its your choice
[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
Enter row1
Enter col1
[[' ' ' ' ' ']
 [' ' 'x' ' ']
 [' ' ' ' ' ']]
navya won


In [31]:
idmat=np.identity(3)
print(idmat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
num1=float(input("enter number"))
num2=float(input("enter number"))
np.add(num1,num2)

enter number14
enter number11


25.0

In [35]:
np1=np.array([3,4,9,5])
np.median(np1)

4.5

In [36]:
np2=np1
np3=np1.copy()

In [37]:
np3[2]=10
print(np3)
print(np1)

[ 3  4 10  5]
[3 4 9 5]


In [32]:
import time
import numpy as np
l1=[i for i in range(10**6)]
np3=np.array(l1)

time_list=time.time()
sum_total=sum(l1)
endtime_list=time.time()
sum2=0
time_numpy=time.time()
sum2=np.sum(np3)
endtime_numpy=time.time()
print("list",endtime_list-time_list)
print("numpy",endtime_numpy-time_numpy)

list 0.007518291473388672
numpy 0.005265235900878906
